# Changes here will be overwritten by Copier
_commit: v1.2.0-28-gc9ac033
_src_path: .
gitattributes_own:
- '* text=auto eol=lf'
github_repository: ZacKienzle2/repo-template
gitignore_own: []
has_discussions: false
has_latex: false
has_node: false
is_public: true
precommit_exclude_own: []
