# The upstream files .gitignore.jinja and .gitattributes.jinja assemble the
# rendered files from, fetched by vendir from each repository's default
# branch. `vendir sync` writes the checked-out commit of each into
# vendir.lock.yml, which is where a copy's upstream revision is recorded, and
# the Vendored files workflow runs the sync weekly and opens a pull request
# with what changed. vendir keeps upstream's licence beside the copies, which
# its legalPaths default names.
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: gitignore
    contents:
      - path: .
        git:
          url: https://github.com/github/gitignore
          ref: origin/main
          depth: 1
        includePaths:
          - Python.gitignore
          - C++.gitignore
          - CMake.gitignore
          - TeX.gitignore
          - Node.gitignore
  - path: gitattributes
    contents:
      - path: .
        git:
          url: https://github.com/gitattributes/gitattributes
          ref: origin/master
          depth: 1
        includePaths:
          - Common.gitattributes
          - C++.gitattributes
          - Python.gitattributes
          - Web.gitattributes
  - path: snakemake-workflow-template
    contents:
      - path: .
        git:
          url: https://github.com/snakemake-workflows/snakemake-workflow-template
          ref: origin/main
          depth: 1
        includePaths:
          - .gitignore
